name: "Build and tests"

on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:    
      - main
      - 'dev'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build with Maven
        run: |
        cd docs-web
        mvn -Dtest=TestDocumentResource test
      
